# -*- coding: utf-8 -*-
"""BuiltinFunction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyUIUpE1I3RCg07AiNFXkDu1Tzf_OZ1B
"""

a = 10
print(float(a))

a = -45
print(abs(a))

str = "hello my name is rajdwip ghosh"
print(len(str))

a = [1,2,3,4,5]
b = sum(a)
print("The result is :",b)

c = (1,2,3,4,5)
d = sum(c)
print("the result is:",d)

a = 10
b = bin(a)
print("The biary value of 10 is :",b)

a = 2+4
b = complex(a)
print(a)

a = [1,2,3,4,5]
starting_value = 10
b = sum(a,starting_value)
print(b)



"""c = 10
d = 5
e = "c+d*2"
print(eval(e))
print(type(e))

```
# This is formatted as code
```

age = int(input("Enter Your age"))
print("Age of this person is :",age)
"""

a = int(input("Enter the first number :"))
b= int(input("Enter the second number :"))
c = a+b
print("The value of A is ",a,"and B is ",b,"sum is :",c)

age = int(input("Enter your age :"))
weight = int(input("Enter your weight :"))
height = float(input("Enter Your Height :"))
correct_age = abs(age)
print("The Correct age is:",correct_age)
BMR = "88.362+(13.397*weight)+(4.799*height)-(5.667*correct_age)"
bmr = eval(BMR)
print("The BMR vslue is :",int(bmr))



s1 =input("Enter Your Name for student1:")
s2 =input("Enter Your Department for student1:")
s3 =int(input("Enter Your age for student1 :"))

print("==========================================")

s4 =input("Enter Your Name for student2:")
s5 =input("Enter Your Department for student2 :")
s6 =int(input("Enter Your age for student2:"))

print("==========================================")

s7 =input("Enter Your Name for student3:")
s8 =input("Enter Your Department for student3:")
s9 =int(input("Enter Your age for student3:"))

print("==========================================")

s10 =input("Enter Your Name for student4:")
s11 =input("Enter Your Department for student4:")
s12 =int(input("Enter Your age for student4:"))

print("==========================================")


s13 =input("Enter Your Name for student5:")
s14 =input("Enter Your Department for student5:")
s15 =int(input("Enter Your age for student5:"))

print("==========================================")

age = (s3+s6+s9+s12+s15)
avg_age = age/5

print("The Average age of the student is :",avg_age)