# -*- coding: utf-8 -*-
"""conditional_coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoUxA-AGzo_ZuKm-WWBANordPaUVnNyL
"""

temp = float(input("Enter the Temparature:"))
if temp<15:
  print("The condition is not suitable")

if 24<temp<28:
  print("This condition is suitable")

age = int(input("Enter Your age :"))
if age>18:
  print("Addhar is Valid for OYO")

else:
  print("Police a Gayaaa!!!")

base_salary = float(input("Enter the salary:"))
years_of_service = int(input("Enter the Year of Service:"))
if years_of_service>5:
  total_salary = base_salary+(0.08*base_salary)-(0.12*base_salary)
  print("Total Salary is:",total_salary)
else:
  net_salary = base_salary - (0.12*base_salary)
  print("Total Salary is:",int(net_salary))

city = input("Enter the name of the City :")
if city == "Mumbai":
  print("Gateway of India")
elif city == "Kolkata":
  print("Victoria Memorial")
elif city == "Pune":
  print("Saniwar Wada")
else:
  print("No record is found")

count = 1
while count<=5:
  print(count)
  count=count+1

num = 1
while num<=50:
  if num%2 == 0:
    print(num)
    num = num+1

a = 1
while 1>0:
  print("I Love You")