# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxqdGbhpJ2ipRnvanNMJxd8FxTNRxvvs
"""

my_dict = {"Name":"Rajdwip",
           "college":"NSEC",
           "dept":"IT",
           "adress":{
               "dist":"howrah",
               "pin":711401


           }}
print(my_dict)