# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOSe1ntSPvjiyCN-elU_kx_tnY9iZ6xX
"""

scores = [55,89,76,65,93,50,72]
for i in scores:
  if i>70:
    print(list[i])
print("Good !Day")

data = [1,2,3,4,5,6,7,8,9,10]
sum = 0
for i in data:
  if i<=5:
    sum = sum+i
    print(sum)

data = [1,2,3,4,5,6,7,8,9,10]
sum_first_five = sum(data[0:5])
print(sum_first_five)

data = [1,2,3,4,5,6,7,8,9,10]
print(data[::-1])

numbers = [1,2,3,4,5,6,7,8,9,10]
print(numbers[0:5])
print(numbers[-5:])

sum_of_last_three_number = sum(numbers[-3:])
print(sum_of_last_three_number)

list_1 = [[1,2],[3,4],[5,6]]
list_2 =[[7,8],[9,10]]
list_3.append(list_1,list_2)
print(list_3)

sentences = ["Hello World","Python is awsome","I love Coding"]
singel_string = "\n".join(sentences)
print(singel_string)

this_list = ["apple","banana"]
this_list.append("Orange")
print(this_list)

a = [1,2,3,4]
a.remove(3)
print(a)

a = [1,2,3,4]
3 in a

a = [1,2,3,4]
5 in a

a = [1,2,3,4]
a.reverse()
print(a)

a = [1,2,3,4]
print(a[::-1])

my_list =[1,2,3,4,5]
my_list[3] = "Hello"
print(my_list)

a=[2,3,4,55,5]
print(len(a))

a=[1,2,3,4,5,6,7,8,9,10]
print(a[::1])