# -*- coding: utf-8 -*-
"""tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYLY0d28tmwhqCtL1qDmNyXS9aMAYg1F
"""

a = (10,20,30)
print(a)
print(type(a))

tup = ()
print(tup)

b = (10,)
print(b)
print(type(b))

a = (1,2,3,(10,20,30))
print(a)

a = ([10,20],[30,40],[50,60])
print(a)
print(type(a))

empty = tuple()
print(empty)

list = [1,2,3,4]
print(list)
print(type(list))

tup = tuple(list)
print(tup)
print(type(tup))

str = "hello"
print(str)
print(type(str))

tup = tuple(str)
print(tup)
print(type(tup))

dict = {'a':1,'b':2,'c':3}
print(dict)
print(type(dict))

tup = tuple(dict)
print(tup)
print(type(tup))

a = {1,2,3}
print(a)
print(type(a))

b = tuple(a)
print(b)

tup = ("apple","banna","cherry","date","mango")
print(tup[0])
print(tup[1:4])
print(tup[:4])
print(tup[-1])

a = (1,2,3,4)
print(a[::-1])

a = (1,2,3,4,5,5)
print(a.count(5))

a = (1,2,3,4)
print(a.index(1))

tup = ("apple","banana","cherry")
print(tup)

l = list(tup)
l.append("date")
print(l)

a = tuple(l)
print(l)

a = (20,30,40)
print(a)

b =list(a)
print(b)

a = (10,20,30,40)
for i in a:
  print(i)

tup1 = (10,20,30)
tup2 = (40,50,60)
tup3 = tup1+tup2
print(tup3)

my_set= {1,2,3}
print(my_set)
print(type(my_set))

my_set = set(1,2,3)
print(my_set)
print(type(my_set))

a = {3,4,1,2}
print(a)

a = {1,2,3,4,4,5}
print(a)

a = {1,2,3,4}
for i in a:
  print(i)

